
#-----------------------------------------------------------------------------------------
# Average distance between spawn attempts for Repurposed Structures Shipwrecks.
# 1 for spawning in most chunks and 1001 for none.
[Shipwrecks]
	#Range: 1 ~ 1001
	netherBricksShipwreckMaxChunkDistance = 29
	#Range: 1 ~ 1001
	crimsonShipwreckMaxChunkDistance = 27
	#Range: 1 ~ 1001
	endShipwreckMaxChunkDistance = 24
	#Range: 1 ~ 1001
	warpedShipwreckMaxChunkDistance = 27

