
#XPiggy Bank Settings
[xpiggybank]
	# The number of ticks between checks for XP orbs in the collection area.
	# Default: 10 (1/2 a second)
	#Range: 1 ~ 1200
	ticks_per_check = 10
	# The internal tank size in mB - each mB = 1xp.
	# This may need to be adjusted based on the conversion rates of the supported fluids. Bear in mind that the
	# fluid with the worst conversion rate will determine the sensible maximum for this value, and the maximum is
	# therefore actually the MAXINT rounded down to nearest 1000 (2147483000) divided by (1000 / (worst rate)) rounded down.
	#
	# Effectively, if all rates are 1000 then you could have 2147483000 as the internal tank size, but if a fluid
	# has a rate lower than 1000, this needs to be adjusted. For example, if you have 'industrialforegoing:essence=100'
	# in your list of fluid types, then the max internal tank size is actually:
	#
	# 2147483000 / (1000 / 100) = 214748300 Mb (214748.3 buckets)
	#
	# However - it's probably not a good idea to have something that large anyway, so in all likelihood you should
	# stick to the default of 20000000 (20000 buckets of Liquid Experience, which is about 2125 levels!)
	#Range: 16000 ~ 2147483000
	internalTankSize = 20000000
	# Whether the pickup of XP orbs in the area is enabled. If set to false, then 
	# the XPiggy Bank can only be used as a tank for converting fluids and storing XP
	# through the GUI.
	pickup_enabled = true
	# The radius around the XPiggy Bank to collect free-floating experience orbs.
	# e.g. a radius of 0 would mean a 1x1 area, a radius of 1 would be 3x3, a radius of 2 would be 5x5, etc.
	# and the default of 4 is a 9x9 area centred on the XPiggy Bank. The max is 12 (25x25) area.
	# For performance reasons, be careful about increasing this too far without also increasing the ticks per check.
	# Default: 4
	#Range: 0 ~ 12
	pickup_radius = 7
	# A semi-colon separated list of additional fluid types, their rate of conversion from 1000 mB to XP, 
	# and whether the fluid can be input, output or both.
	#
	# For example:
	#   sophisticatedbackpacks:xp_still=1000:IO;industrialforegoing:essence=100:I;cofh_core:experience=1000:IO;minecraft:water=10:O
	# This example would mean that: 
	#   - every 1000mb of Sophisticated Backpack's XP would be equivalent to 1000XP (1:1 conversion) and can be input or output
	#   - every 1000mb of Industrial Foregoing's Essence would be equivalent to 100XP (10:1 conversion) but can only be input
	#   - every 1000mb of COFH Core's Experience would be equivalent to 1000XP (1:1 conversion) and can be input or output
	#   - every 1000mb of water would be equivalent to 10XP (100:1 conversion) but can only be output
	fluids = "sophisticatedbackpacks:xp_still=1000:IO;industrialforegoing:essence=100:IO;cofh_core:experience=1000:IO"

#JEI Settings
[jei]
	# Enable or disable the Click Area inside the GUI in all Cuboid machines.
	enable_jei_click_area = true
	# Enable or disable the Catalysts in Jei for Cuboid machines.
	enable_jei_catalysts = true
	# Enable or disable the JeiPlugin of Cuboid machines.
	enable_jei = true

#Misc
[misc]
	# Logs additional information when loading.
	verbose_logging = false

